os: linux
language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - yarn test --watchAll=false
  - yarn build

deploy:
  provider: pages
  edge: true
  cleanup: false
  token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master
